- name: Developer Environment Setup
  hosts: all
  gather_facts: true
  tasks:
    - name: Include zsh role
      when: zsh_enabled | default(false)
      ansible.builtin.include_role:
        name: zsh
    - name: Include brew role
      when: brew_enabled | default(false)
      ansible.builtin.include_role:
        name: brew
    - name: Include git role
      when: git_enabled | default(false)
      ansible.builtin.include_role:
        name: git
    - name: Include starship role
      when: starship_enabled | default(false)
      ansible.builtin.include_role:
        name: starship
    - name: Include direnv role
      when: direnv_enabled | default(false)
      ansible.builtin.import_role:
        name: direnv
    - name: Include python role
      when: python_enabled | default(false)
      ansible.builtin.include_role:
        name: python
    - name: Include warp.dev terminal role
      when: warp_enabled | default(false)
      ansible.builtin.include_role:
        name: warp
    - name: Include kubernetes role
      when: kubernetes_enabled | default(false)
      ansible.builtin.import_role:
        name: kubernetes
    - name: Include onepassword role
      when: onepassword_enabled | default(false)
      ansible.builtin.import_role:
        name: onepassword
    - name: Include nvm role
      when: nvm_enabled | default(false)
      ansible.builtin.import_role:
        name: nvm
    - name: Include tfenv role
      ansible.builtin.import_role:
        name: tfenv
      when: tfenv_enabled | default(false)
    - name: Ensure precommit is installed
      ansible.builtin.import_role:
        name: precommit
      when: precommit_enabled | default(false)
    - name: Ensure httpie is installed
      ansible.builtin.import_role:
        name: httpie
      when: httpie_enabled | default(false)
    - name: Include nerdfonts role
      when: nerdfonts_enabled | default(false)
      ansible.builtin.import_role:
        name: nerdfonts
    - name: Include podman role
      when: podman_enabled | default(false)
      ansible.builtin.import_role:
        name: podman
    - name: Include neovim role
      when: nvim_enabled | default(false)
      ansible.builtin.import_role:
        name: nvim
