---
- name: Developer Environment Setup
  hosts: localhost
  vars:
    enable_brew: true
    enable_git: true
    enable_zsh: true
    enable_nerd_fonts: true
    enable_starship: true
    enable_direnv: true
    enable_podman: true
    enable_nvim: true
    preffered_font: "FiraCode"
    starship_theme_preset: "tokyo-night"
  pre_tasks: []
  handlers: []
  tasks:
    - name: Include brew role
      ansible.builtin.include_role:
        name: brew
      when: enable_brew | default(true)
    - name: Include git role
      ansible.builtin.include_role:
        name: git
      vars:
        git_username: "Anirudh Aggarwal"
        git_email: "16053724+ani1797@users.noreply.github.com"
      when: enable_git | default(true)
    - name: Include podman role
      ansible.builtin.include_role:
        name: podman
      when: enable_podman | default(false)
    - name: Include zsh role
      ansible.builtin.include_role:
        name: zsh
      when: enable_zsh | default(false)
    - name: Include nerdfonts role
      ansible.builtin.include_role:
        name: nerdfonts
      vars:
        nerdfonts_fonts:
          - "{{ preffered_font }}"
      when: enable_nerd_fonts | default(false)
    - name: Include starship role
      ansible.builtin.include_role:
        name: starship
      when: enable_starship | default(false)
    - name: Include direnv role
      ansible.builtin.include_role:
        name: direnv
      when: enable_direnv | default(false)
    - name: Include nvim role
      ansible.builtin.include_role:
        name: nvim
      when: enable_nvim | default(false)
    - name: Include kubernetes role
      ansible.builtin.include_role:
        name: kubernetes
  post_tasks: []
  roles: []
