---
- name: Configure git user name
  when: git_username is not none
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"
- name: Configure git user email
  when: git_email is not none
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
- name: Setup main branch name
  when: git_default_branch is not none
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: "{{ git_default_branch }}"
- name: Set up git aliases
  community.general.git_config:
    name: "alias.{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ git_aliases | dict2items }}"
- name: Enable color UI
  community.general.git_config:
    name: color.ui
    scope: global
    value: auto
- name: Ensure git global config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/git"
    state: directory
    mode: 0700
- name: Load the global gitignore from toptal
  when: 
    - git_setup_global_ignore | default(true)
    - git_toptal_ignore_templates | length > 0
  ansible.builtin.get_url:
    url: "{{ git_toptal_url }}/api/{{ git_toptal_ignore_templates | join(',') }}"
    dest: "{{ ansible_env.HOME }}/.config/git/.gitignore"
    mode: 0700
- name: Configure global gitignore file
  when:
    - git_setup_global_ignore | default(true)
    - git_toptal_ignore_templates | length > 0
  community.general.git_config:
    name: core.excludesFile
    scope: global
    value: "{{ ansible_env.HOME }}/.config/git/.gitignore"
- name: Ensure user-defined configs are applied
  when: git_user_configs is defined
  community.general.git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ git_user_configs | dict2items }}"
  loop_control:
    label: "{{ item.key }} = {{ item.value }}"
