---
- name: Ensure git is installed (Linux)
  become: true
  when: ansible_os_family != "Darwin"
  ansible.builtin.package:
    name: git
    state: present
- name: Ensure git is installed (macOS)
  when: ansible_os_family == 'Darwin'
  community.general.homebrew:
    name: git
    state: present
