---
- name: Ensure git is installed (Debian/Ubuntu/WSL)
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.package:
    name: git
    state: present
- name: Ensure git is installed (RedHat/Fedora)
  become: true
  when: ansible_os_family == "RedHat"
  ansible.builtin.yum:
    name: git
    state: present
- name: Ensure git is installed (Arch Linux)
  become: true
  when: ansible_os_family == "Archlinux"
  community.general.pacman:
    name: git
    state: present
- name: Ensure git is installed (macOS)
  when: ansible_os_family == 'Darwin'
  community.general.homebrew:
    name: git
    state: present
