---
- name: Ensure git is installed
  tags: install
  become: true
  ansible.builtin.package:
    name: git
    state: present
- name: Verify git installation
  tags: verify
  ansible.builtin.command: git --version
  register: git_version_output
  changed_when: false
- name: Display git version
  tags: debug
  ansible.builtin.debug:
    var: git_version_output.stdout
- name: Configure git user name
  tags: config
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"
  when: git_username is not none
- name: Configure git user email
  tags: config
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  when: git_email is not none
- name: Set up git aliases
  tags: config
  community.general.git_config:
    name: "alias.{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ git_aliases | dict2items }}"
- name: Setup main branch name
  tags: config
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: "{{ git_default_branch }}"
  when: git_default_branch is not none
- name: Ensure git global config directory exists
  tags: config
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/git"
    state: directory
    mode: '0730'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
- name: Load the global gitignore from toptal
  tags: config
  ansible.builtin.get_url:
    url: "{{ git_toptal_url }}/api/{{ git_toptal_ignore_templates | join(',') }}"
    dest: "{{ ansible_env.HOME }}/.config/git/.gitignore"
    mode: '0644'
  when: git_setup_global_ignore | default(true) and git_toptal_ignore_templates | length > 0
- name: Configure global gitignore file
  tags: config
  community.general.git_config:
    name: core.excludesFile
    scope: global
    value: "{{ ansible_env.HOME }}/.config/git/.gitignore"
  when: git_setup_global_ignore | default(true) and git_toptal_ignore_templates | length > 0