---
- name: Ensure uv in installed
  community.general.homebrew:
    name: uv
    state: present
- name: Detect the direnv plugins directory
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/direnv/lib"
  register: direnv_lib_dir
- name: Copy the uv direnv extension
  ansible.builtin.copy:
    src: uv.sh
    dest: "{{ ansible_env.HOME }}/.config/direnv/lib/uv.sh"
    mode: '0755'
  when: direnv_lib_dir.stat.exists
- name: Ensure the uv configuration directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/uv"
    state: directory
    mode: '0755'
- name: Copy the uv.toml configuration file
  ansible.builtin.template:
    src: uv.toml.j2
    dest: "{{ ansible_env.HOME }}/.config/uv/uv.toml"
    mode: '0644'
