---
- name: Install tmux on non macOS systems
  ansible.builtin.package:
    name: tmux
    state: present
  when: ansible_facts['os_family'] != 'Darwin'
- name: Install tmux on macOS systems
  community.general.brew:
    name: tmux
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
