# Windows specific variables for Nerd Fonts installation
---
nerdfonts_install_path: "C:/Program Files/NerdFonts"
nerdfonts_font_ext: "ttf"
nerdfonts_temp_dir: "C:/Users/{{ ansible_user_id }}/AppData/Local/Temp"
