---
- name: Ensure direnv directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/direnv/lib"
    state: directory
    mode: '0700'
  when:
    - enable_direnv | default(false)
    - precommit_enabled | default(false)
    - precommit_direnv_integrated | default(false)
- name: Ensure precommit directory exists
  ansible.builtin.copy:
    src: precommit.sh
    dest: "{{ ansible_env.HOME }}/.config/direnv/lib/precommit.sh"
    mode: '0700'
  when:
    - enable_direnv | default(false)
    - precommit_enabled | default(false)
    - precommit_direnv_integrated | default(false)
