---
- name: Ensure direnv directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/direnv/lib"
    state: directory
    mode: '0744'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
- name: Ensure precommit directory exists
  ansible.builtin.copy:
    src: precommit.sh
    dest: "{{ ansible_env.HOME }}/.config/direnv/lib/precommit.sh"
    mode: '0744'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
