$ANSIBLE_VAULT;1.1;AES256
61656161393564336532613361633861346532656137346466663538306332656562393932653161
3764613032303131306363336361656230303334323039300a313934316235396439373035323763
36376638323637316661623966313763613366353138363231393364396234613337383731356163
3962653537633735390a373163633861373736383264393663313465653037336465663430356466
36333131313532613637383434613264313261353034343135396365343231616139376337376631
3461386539376662373438666535656234666365323664383335
